refactor(slideshow): rework slideshow design
ovh/ovh-ui-kit pull request #702
Opened 2020-11-12 16:02 UTC by Heiiji

Signed-off-by: jjuret <julien.juret@gmail.com>

## Refacto Slideshow component for new design

### Description of the Change

A new design, component logic stay the same

2020-11-12 18:08 UTC, antleblanc requested changes

2020-11-12 18:08 UTC, antleblanc commented on packages/components/slideshow/src/js/panel/slideshow-panel.html
> +    <div ng-if="::$ctrl.picture" class="oui-slideshow-panel__picture"
Not mandatory but we tend to group native attributes and then directives (custom properties).
Could you please move `ngIf` right after the `class` attribute?

2020-11-12 18:08 UTC, antleblanc commented on packages/components/slideshow/src/js/panel/slideshow-panel.html
> +    <div class="oui-slideshow-panel-oblique" ></div>
```suggestion
    <div class="oui-slideshow-panel-oblique"></div>
```

2020-11-12 18:08 UTC, antleblanc commented on packages/components/slideshow/src/less/slideshow.less
> +      top: 5px;
Couldn't be stored as a variable into following file?
- `packages/base/core/src/less/variables/components/slideshow.less`

`px` unit is mainly used to border size. Could you please use `rem-calc`?

2020-11-13 08:47 UTC, antleblanc approved these changes

2020-11-13 08:48 UTC, JeremyDec approved these changes

2020-11-13 09:01 UTC, merged