Feat/modularise UI kit
ovh/ovh-ui-kit pull request #709
Opened 2021-03-10 06:25 UTC by radireddy

### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions

## Title of the Pull Requests 

Components modularization

### Description of the Change

Below changes are made 
1. Move all styles, icons, and flags from @ovh-ux/ui-kit.core to @ovh-ux/ui-kit.css package
2. Delete package @ovh-ux/ui-kit.core
3. Replace all references of @ovh-ux/ui-kit.core with @ovh-ux/ui-kit.css
4. Move package @ovh-ux/ui-kit.components from /packages/base to /packages.
5. Build and export each component separately. This enables users to only import components they require.
6. Update docs to use component modularization.

### Benefits

Added support for component modularization. This enables users to only import components they require. This improves page load performance by reducing bundle size.

### Possible Drawbacks

### Applicable Issues

2021-03-10 10:31 UTC, JeremyDec commented on packages/css/webpack.config.js
> +    filename: '[name].js',
**question**:
Do you need to produce js file output for this package ? I mean, can we have just a css output file here, as that is what the package is supposed to provide ?

2021-03-10 13:22 UTC, zakariasahmane commented
Hi Ravi ! 

I see here that we use webpacks to generate chunks of each component. 
That can be heavy to maintain because the webpack config is closely tied to the code. 

Couldn't we use ES6 modules instead? I don't know if it's possible to do so in this context ( and i also don't know how it was made before), but i think that there is an option in the package.json called "module" which is given one js file that contains es modules, and i think that this option tell the bundlers that we want to allow ES Modules and therefore allow the treeshaking for the package.
This way, we can import a specific component without importing the whole library thanks to the treeshaking. 

I am not sure of this being available with angular.js and if it's even possible, it's just an idea thrown out there but i know that's how many modern libraries allow the treeshaking thus making their libs lighter.

2021-03-10 14:02 UTC, JeremyDec requested changes

2021-03-10 14:40 UTC, JeremyDec commented on packages/components/README.md
> +Refer to component README file for more details.
**suggestion**
Maybe you could directly show an example with `oui-button`. (For `js` or `html` part)

2021-03-10 14:40 UTC, JeremyDec commented on packages/components/README.md
> +## Documentation
You could also mention the Storybook documentation url: https://ovh.github.io/ovh-ui-kit/

2021-03-12 08:41 UTC, marie-j commented on packages/apps/workshop/README.md
> +yarn build:dependency
Shouldn't this be integrated in `yarn:start` ? I'm not sure we should be worrying what to start and to build when starting storybook. For instance in `manager` repository we have the `start:dev` command that will handle the build of needed dependencies so we don't have to worry about it

2021-03-12 08:41 UTC, marie-j commented on packages/components/action-menu/src/index.less
> -@import './less/action-menu';
I'm having trouble understanding the removal of the less file. Shouldn't the component still import its style to be standalone ?
`@import './less/action-menu';`

2021-03-12 08:41 UTC, marie-j commented on packages/apps/workshop/stories/documentation/migrate/from-v4-to-v5.story.mdx
> +<Description>{readme}</Description>
SHould be completed ?

2021-03-12 08:41 UTC, marie-j commented on packages/components/webpack.config.js
> +    ],
Not really easy to maintain, if we want to add a component, we have to update the webpack.config

2021-03-12 08:41 UTC, marie-j commented on packages/css/src/less/components/atoms.less
> +@import './button/index';
Why some files are located in `./less` and some directly in `./{component}`. Shouldn't we be consistent ?

2021-03-12 08:41 UTC, marie-j commented on packages/css/webpack.config.js
> +    // libraryTarget: 'umd',
```suggestion

```

2021-03-12 08:41 UTC, marie-j commented on packages/css/webpack.config.js
> +    path: path.resolve('.', 'dist', 'js'),
Storing CSS dist in `/js` ?

2021-03-12 08:41 UTC, marie-j commented on packages/libs/ui-kit/README.md
> +<link rel="stylesheet" href="path/to/@ovh-ux/ui-kit/dist/css/oui.css">
So this means that we need to bring the whole style for only one component ? Shouldn't the component bring its own style ?

2021-03-17 16:36 UTC, JeremyDec commented on packages/apps/workshop/stories/design-system/components/action-menu/action-menu-webcomponent.stories.js
> +import '@ovh-ux/ui-kit/dist/js/oui-action-menu';
This is breaking the functioning of workshop application.
As you can see below with the `README.md` import, you can import without precising the path of the main file.

```suggestion
import '@ovh-ux/ui-kit.action-menu';
```

2021-03-17 16:36 UTC, JeremyDec commented on packages/apps/workshop/stories/design-system/components/button/button-webcomponent-primary.stories.js
> +import ouiButton from '@ovh-ux/ui-kit/dist/js/oui-button';
To keep consistency with other stories
```suggestion
import '@ovh-ux/ui-kit/dist/js/oui-button';
```

2021-03-18 07:42 UTC, JeremyDec requested changes

2021-03-18 07:42 UTC, JeremyDec commented on packages/apps/workshop/stories/design-system/components/action-menu/action-menu-webcomponent.stories.js
> +import '@ovh-ux/ui-kit/dist/js/oui-action-menu';
This is breaking the functioning of workshop application.
As you can see below with the `README.md` import, you can import without precising the path of the main file.

```suggestion
import '@ovh-ux/ui-kit.action-menu';
```

2022-06-10 05:53 UTC, closed without merging