feat(dropdown): handle target top
ovh/ovh-ui-kit pull request #780
Opened 2022-04-04 10:10 UTC by zakariasahmane

Signed-off-by: Zakaria Sahmane <zakaria.sahmane@corp.ovh.com>

### Description of the Change
Handle the target="_top" of links in the oui-action-menu-item

### Benefits
Possibility to add target top to action item menu entries.

2022-04-05 06:10 UTC, antleblanc requested changes
Changes looks good to me, except that you missed to add some tests.

2022-04-05 14:26 UTC, frenautvh submitted a review, later dismissed

2022-04-06 08:51 UTC, antleblanc approved these changes

2022-04-06 12:49 UTC, frenautvh approved these changes

2022-04-06 13:50 UTC, merged