feat(field): removed restriction on error display
ovh/ovh-ui-kit pull request #833
Opened 2023-12-05 10:59 UTC by JacquesLarique

ref: DTRSD-123286

Title of the Pull Requests
Display error messages whitout user interaction

Description of the Change
Removed the restrictions to display errors

2023-12-05 11:05 UTC, anooparveti commented on packages/components/field/src/js/field.controller.js
> +    return this.invalid;
**nitpick:** Error should be displayed only if the field already has a value.

2023-12-05 13:50 UTC, anooparveti requested changes

2023-12-05 13:50 UTC, anooparveti commented on packages/components/field/src/js/field.controller.js
> +      && (this.form[this.currentErrorField].$modelValue || this.blurred || this.form.$submitted);
**nitpick:** Condition should be updated to check if there is any value on the `input` element associated with this particular `oui-field`

2023-12-13 07:17 UTC, anooparveti approved these changes

2023-12-13 08:01 UTC, BrunoMarquesOVH approved these changes

2023-12-13 08:02 UTC, qpavy approved these changes

2023-12-14 12:47 UTC, merged