feat(components): Add some tooltip options to existing components
ovh/ovh-ui-kit pull request #842
Opened 2024-02-22 17:09 UTC by JayBeeDe

### Requirements

## Title of the Pull Requests

Add some tooltip options to existing components

### Description of the Change

Add some tooltip options to following components:
- oui-switch
- oui-calendar
- oui-timepicker
- oui-inline-adder
- oui-numeric

### Benefits

Add a tooltip action to components that have button or where there is something to click

### Possible Drawbacks

Might be overkill in some cases, to be used with moderation.

### Applicable Issues

MANAGER-13561

2024-02-22 17:21 UTC, ovh-cds commented
CDS Report yarn-build#2878.0 ✘  
* build & test
  * build ✔ 
  * test ✘

2024-02-26 11:55 UTC, anooparveti requested changes

2024-02-26 11:55 UTC, anooparveti commented on packages/components/switch/src/js/switch.controller.js
**nitpick:** We cannot depend on the `onChange`. What if user updates the value in their controller?
Maybe we can just accept the tooltip and dev updates the tooltip as and when the user interacts with it.

2024-02-26 14:20 UTC, JayBeeDe commented on packages/components/switch/src/js/switch.controller.js
@anooparveti done

2024-02-27 09:37 UTC, dectotam commented on packages/components/timepicker/src/js/timepicker.component.js
> +    tooltip: '@?',
```suggestion
    tooltip: '@?',
```

2024-02-27 09:37 UTC, dectotam approved these changes, later dismissed

2024-02-28 13:50 UTC, dectotam approved these changes

2024-02-28 13:54 UTC, anooparveti approved these changes

2024-02-29 13:18 UTC, benjaminlepine approved these changes

2024-03-18 13:33 UTC, merged